feishu:
  app_id: cli_a917f016a8795bd2
  app_secret: slm61g5YtraWOYRHHnK9DhroCVwJEPB7
  enabled: false
  sheet_id: 999fda
  token: URxNs0fxmhE1TKtK91HcScvVnGf
  user_open_id: ou_e401d376ae91c0a54721d7da0ef5fd5c
fire_price:
  mode: 赛季普通
  scrape_enabled: true
  scrape_interval: 300
items:
  auto_reload: true
  json_path: data/full_table.json
  reload_interval: 300
server:
  access_code: tlifire2026
  port: 19877
